[package]
name = "i405-tunnel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1"
bytes = "1"
clap = "4.5"
enumflags2 = "0.7.11"
enum_dispatch = "0.3.13"
env_logger = "0.11"
log = "0.4"
thiserror = "2"
tun-rs = "2.0"
wolfssl.branch = "markasoftware/psk-and-rw-signatures"
wolfssl.git = "https://github.com/markasoftware/wolfssl-rs"

[features]
wolfssl-debug = ["wolfssl/debug"]
jumbo-packets = []