[package]
name = "i405-tunnel"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
clap = "4.5"
env_logger = "0.11"
log = "0.4"
tun-rs = "2.0"
wolfssl.git = "https://github.com/markasoftware/wolfssl-rs"
wolfssl.branch = "markasoftware/psk-and-rw-signatures"
